### ISSUE TITLE
เอาโค้ดของ GameP และ GameB มารวมกันแล้ว

### ISSUE THREAD

**Issue by PremerX007** [SkyEngineerME/Blackjack#15]
อาจจะต้องปรับอีกเยอะ เพราะนี่ยังไม่ได้ optimize อะไรเลย อ่านยากหน่อยนะ หรือ @Th3than จะปรับต่อก็เอาเลย
https://github.com/SkyEngineerME/Blackjack/blob/main/integrateGamefunc.cpp

**Comment by PremerX007** [comment]
![image](https://user-images.githubusercontent.com/39229888/221240931-6cf534cf-339f-4aa5-904e-92c4077b8e23.png)

**Comment by SkyEngineerME** [comment]
ขอบคุณเปรมมากเลย ต่อไปวางโปรแกรมหลักง่ายขึ้นเยอะ

**Comment by PremerX007** [comment]
เราได้เขียนอีกแบบนึงที่เป็น object class สำรองเผื่อไว้ เผื่อจะได้เพิ่ม feature ที่เหลือให้ทำได้ง่ายขึ้น 
ให้ push ขึ้น github เอาไว้ไหม? @SkyEngineerME

**Comment by SkyEngineerME** [comment]
โอ้วโอเคผมทำรวมฟังก์ชั่นแยกไปอีกอันนึงแล้วขอโทษทีนะครับ แต่push ขึ้น Git มาเลยก็ได้ครับ

**Comment by PremerX007** [comment]
เอาไปดูเล่นๆก็ได้ครับ แล้วแต่ท่านเลย555 เดี๋ยว push ให้ครับ

**Comment by SkyEngineerME** [comment]
รบกวนด้วยครับ
