### ISSUE TITLE
Blackjackgame

### ISSUE THREAD

**Issue by SkyEngineerME** [SkyEngineerME/Blackjack#16]
เกมหลักรวมฟังก์ชั่นทั้งหมด

**Comment by SkyEngineerME** [comment]
1 Try (นำฟังก์ชั่นทั้งหมดมาไว้ในโปรแกรมหลักหมดแล้วและมีการเปลี่ยนแปลงfunction leaderboard เป็น Statโดยเก็บข้อมูลของผุ้เล่นในทุกๆตา）

**Comment by SkyEngineerME** [comment]
@PremerX007  โค้ดมันมีให้กด arrow left right แล้วใน visual มันกดไม่ได้มันต้องไปรัน code ที่ไหนครับ

**Comment by PremerX007** [comment]
กดรันผ่าน coderunner ใช่เปล่า ถ้างั้นต้องเข้าไปตั้งค่า run in terminal ตามนี้
![image](https://user-images.githubusercontent.com/39229888/222945905-b6df2541-a784-4f09-83c1-f42ae94c5945.png)
![Screenshot 2023-03-05 134356](https://user-images.githubusercontent.com/39229888/222945972-df446df9-f55f-4e11-a084-09826a596648.png)

@SkyEngineerME

**Comment by SkyEngineerME** [comment]
@PremerX007 เราsettingแล้วมันก็กดไม่ได้อะ เปรมก็รันในvisual ใช่มั้ย

**Comment by SkyEngineerME** [comment]
โค้ด(ต่อจากโค้ดเปรม)"วางแผนlistต่างๆ"
1.เพิ่มchoiceว่าจะเล่นกี่ turn
2.bot dealer
3.เทียบคะแนนกับdealer
4.ส่งค่าข้อมูลของ player
5.เงินเดิมพัน

**Comment by PremerX007** [comment]
> @PremerX007 เราsettingแล้วมันก็กดไม่ได้อะ เปรมก็รันในvisual ใช่มั้ย

ใช่ๆ มันเป็นยังไง อัดคลิปมาดูหน่อย

**Comment by SkyEngineerME** [comment]
https://user-images.githubusercontent.com/75652796/223093013-f73856b3-bce9-4b1d-b34a-6aa7e74efc34.MOV

**Comment by SkyEngineerME** [comment]
เหลือ
1.เทียบคะแนนกับ dealer
2.ส่งสถิติ
3.เงินเดิมพัน

**Comment by SkyEngineerME** [comment]
flowchart เทียบคะแนนdealer และส่งค่าสถานะเป็น int condition โดย 0 = win, 1= draw,2=lose.![image](https://user-images.githubusercontent.com/75652796/223744741-4aed9abc-9392-4af0-8c17-f7d0184960c9.jpeg)
![image](https://user-images.githubusercontent.com/75652796/223744992-c0238cb2-0fd9-4c2d-83e1-93c7b7ba72de.jpeg)

**Comment by PremerX007** [comment]
โค้ดเรามันสเกลจำนวนบอทได้นะ การ fix จำนวน parameter อาจเป็นเรื่องที่ไม่ค่อย work เท่าไหร่ แต่เราจะเอาโค้ดที่เฟิร์สเขียนไปใช้นะ จะปรับให้เข้ากับตัวระบบให้ได้ ✊

**Comment by SkyEngineerME** [comment]
เราคิดว่าถ้าsetในเงื่อนไขว่าถ้าคะแนนเป็น 0จะถือว่าไม่ลงเล่น น่าจะเป็นไอเดียที่ดี

**Comment by PremerX007** [comment]
เออหว่ะ ทำไมเราคิดไม่ได้555 เครเลย

**Comment by SkyEngineerME** [comment]
เสร็จหมดแล้ว
