### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by SkyEngineerME** [SkyEngineerME/Blackjack#18]
ใส่ bug ที่เจอ

**Comment by Th3than** [comment]
[](url)
![Screenshot 2023-03-08 231637](https://user-images.githubusercontent.com/110963328/223771235-175b0db8-1828-4d3f-ade6-2acf8f326abf.png)
![Screenshot 2023-03-08 231752](https://user-images.githubusercontent.com/110963328/223771243-3a66b373-1fea-4ccb-a04d-740b612a74c9.png)
บอทจั่วไพ่รั่วๆ 
และเจอบ้างกรณีกดHit หรือ stand แล้วเด้งมา New game

**Comment by SkyEngineerME** [comment]
![image](https://user-images.githubusercontent.com/75652796/223777717-e4f75da7-0bd7-4a85-a257-a5d2580bd3b4.jpeg)
บอทปิดไพ่แต่โชว์สกอถูกต้อฃ

แก้ไขการซ่อนไพ่เรียบร้อย

**Comment by PremerX007** [comment]
> ![Screenshot 2023-03-08 231637](https://user-images.githubusercontent.com/110963328/223771235-175b0db8-1828-4d3f-ade6-2acf8f326abf.png) ![Screenshot 2023-03-08 231752](https://user-images.githubusercontent.com/110963328/223771243-3a66b373-1fea-4ccb-a04d-740b612a74c9.png) บอทจั่วไพ่รั่วๆ และเจอบ้างกรณีกดHit หรือ stand แล้วเด้งมา New game

เช็คแล้ว ตกปีกกา 5555 ไปเข้า loop tryagain แจกการ์ดกระหน่ำเลยทีนี้ แก้ละๆ

**Comment by SkyEngineerME** [comment]
![image](https://user-images.githubusercontent.com/75652796/224329197-379a45f2-7af7-4e52-9ee4-3384bee4f1a4.jpeg)
Dealer ได้ blackjack เกมเลยไม่เริ่ม

**Comment by Th3than** [comment]
![image](https://user-images.githubusercontent.com/110963328/224334351-fcea6f93-71eb-4ebb-a8d1-7d47d93e673e.png)
ดิลเลอร์โชว์แต้มที่ปิดไว้

**Comment by Th3than** [comment]
![image](https://user-images.githubusercontent.com/110963328/225001875-6546ff99-efa6-4aa0-a120-00a98aa8d029.png)
blackjacck ชน dealer แต่ขึ้นว่าชนะ และแต้ม dealer เปิดแค่ k แต่ขึ้น 20

**Comment by Th3than** [comment]
![Screenshot 2023-03-14 192912](https://user-images.githubusercontent.com/110963328/225002180-234a582e-6104-45cf-8e8b-33d8386f0c25.png)
ไม่บอกว่าบอทตัวไหนbetเท่าไร

**Comment by PremerX007** [comment]
> ![Screenshot 2023-03-14 192912](https://user-images.githubusercontent.com/110963328/225002180-234a582e-6104-45cf-8e8b-33d8386f0c25.png) ไม่บอกว่าบอทตัวไหนbetเท่าไร

แก้ละ

**Comment by PremerX007** [comment]
> ![image](https://user-images.githubusercontent.com/110963328/224334351-fcea6f93-71eb-4ebb-a8d1-7d47d93e673e.png)
> ดิลเลอร์โชว์แต้มที่ปิดไว้

![IMG_1463](https://user-images.githubusercontent.com/39229888/225036213-3bd9cdaa-ad44-47a0-bda0-b4f8d4ecd7d7.jpeg)
เจอบัคแล้ว  แก้เรียบร้อย
