### ISSUE TITLE
Tester

### ISSUE THREAD

**Issue by SkyEngineerME** [SkyEngineerME/Blackjack#19]
เช็คโปรแกรม
เล่น 2 ตา (บอท1,2,3 อย่างละรอบ)

เล่น 10 ตา (บอท1,2,3 อย่างละรอบ)

เล่น 50 ตา (บอท1ตัว 1รอบ)

**Comment by ExtraStudent101** [comment]
รอบที่1:เกมสรุปผลแต่playerยังไม่ทันได้เล่น เพรราะดีลเลอร์ได้แบล็คแจ็ค
![image](https://user-images.githubusercontent.com/110962678/224494830-b806cfa1-459c-4c36-9612-625a3487b44e.png)

**Comment by PremerX007** [comment]
ที่เจออีกจุดนึงคือคำว่า Lose มาจากหนายยยย TT

**Comment by ExtraStudent101** [comment]
มี่ค่า -1$ ขึ้นในscoreboard โดยไม่ทราบที่มา
![image](https://user-images.githubusercontent.com/110962678/224495026-aaa46578-106e-479a-a934-254539530486.png)

**Comment by SkyEngineerME** [comment]
> ที่เจออีกจุดนึงคือคำว่า Lose มาจากหนายยยย TT

อาจจะอยู่ใน checkmoney()อาจจะลืมเอาออกตอน assign condition

**Comment by PremerX007** [comment]
> มี่ค่า -1$ ขึ้นในscoreboard โดยไม่ทราบที่มา ![image](https://user-images.githubusercontent.com/110962678/224495026-aaa46578-106e-479a-a934-254539530486.png)

เพื่อนรบกวนแปะรูปค่าใน scoreboard.txt มาด้วยหน่อย

**Comment by ExtraStudent101** [comment]
> 

![image](https://user-images.githubusercontent.com/110962678/224495179-6ea528ee-77e1-4c0f-941e-6e3107953307.png)

**Comment by ExtraStudent101** [comment]
จากที่ลองเล่น น่าจะมีการบอกตั้งแต่แรกว่าเงื่อนไขการเดิมพันต้องไม่เกินเท่าไร
![image](https://user-images.githubusercontent.com/110962678/224495216-49d92225-00d2-46c8-819e-ff5790ed728b.png)

**Comment by ExtraStudent101** [comment]
ในเกมที่2 ผมได้เล่นกับบอท1ตัว 2รอบ ซึ่งรอบแรกลงเงิน6$แล้วแพ้ รอบที่สองลงเงิน10$ ชนะแต่กลับไม่ได้เงินเพิ่ม 
![image](https://user-images.githubusercontent.com/110962678/224495766-d5094b04-42c3-40d2-945b-8dcf08bb7357.png)

**Comment by ExtraStudent101** [comment]
เกมไม่ควรจบรอบทันทีที่มีผู้เล่นได้แบล็คแจ็ค ควรสู้ต่อได้
![image](https://user-images.githubusercontent.com/110962678/224496183-01fba3de-926e-4d1f-b31b-3cd5440c4f0c.png)

**Comment by ExtraStudent101** [comment]
อิหยังครับนิตรงชื่อบอท
![image](https://user-images.githubusercontent.com/110962678/224498490-bf2204ef-4c76-48eb-8a7e-c10b0d44890f.png)

**Comment by PremerX007** [comment]
> อิหยังครับนิตรงชื่อบอท ![image](https://user-images.githubusercontent.com/110962678/224498490-bf2204ef-4c76-48eb-8a7e-c10b0d44890f.png)

อันนี้ทะแม่งๆตั้งแต่ทำโปรแกรมละ 5555 แต้งกิ้วที่เทสให้เจอ

**Comment by SkyEngineerME** [comment]
> จากที่ลองเล่น น่าจะมีการบอกตั้งแต่แรกว่าเงื่อนไขการเดิมพันต้องไม่เกินเท่าไร ![image](https://user-images.githubusercontent.com/110962678/224495216-49d92225-00d2-46c8-819e-ff5790ed728b.png)

เรียบร้อยบอกงเงินเดิมพันแล้ว

**Comment by ExtraStudent101** [comment]
![image](https://user-images.githubusercontent.com/110962678/225013329-c0c1391f-043f-4799-b100-06ee934a4350.png)

**Comment by SkyEngineerME** [comment]
เหลือแค่เคสแบล็คแจ็ค

**Comment by ExtraStudent101** [comment]
บัคการเช็คคะแนน
![image](https://user-images.githubusercontent.com/110962678/225055075-f597ab44-f1f2-4ce0-92f1-08402fa5c80c.png)

**Comment by ExtraStudent101** [comment]
![image](https://user-images.githubusercontent.com/110962678/225055856-a6ab88ff-95bb-4217-bdbd-e7651e0da385.png)

**Comment by ExtraStudent101** [comment]
playerแพ้แล้วDealerก็แพ้เหมือนกัน ควรได้Draw
![image](https://user-images.githubusercontent.com/110962678/225058920-7a1ba333-1fdb-4a45-9220-f700cf7e3d09.png)

**Comment by ExtraStudent101** [comment]
ลงเงินเดิมพัน69แต่เกมแสดงเลขเป็น414 แต่ระบบเพิ่มเงินก็เพิ่มเงิน69ตามปกติ
![image](https://user-images.githubusercontent.com/110962678/225600769-1855ceb5-3d58-44d8-8d69-3b892d710e94.png)
