### ISSUE TITLE
LeaderBoard()

### ISSUE THREAD

**Issue by SkyEngineerME** [SkyEngineerME/Blackjack#2]
ฟังก์ชั่นบันทึกสถิติและจัดอันดับของผู้เล่นทุกตา

**Comment by SkyEngineerME** [comment]
ยังไม่มีไอเดียว่าจะบันทึกข้อมูลทุกครั้งอย่างไร

**Comment by Th3than** [comment]
https://drive.google.com/drive/folders/1Z6oQJnZPV-w-hawlw2oiV-DkFxOCEIGE

**Comment by Th3than** [comment]
Lecture 11 หน้า 6
