### ISSUE TITLE
GameB()

### ISSUE THREAD

**Issue by SkyEngineerME** [SkyEngineerME/Blackjack#3]
ฟังก์ชั่นให้ Bot เลือกที่จะหมอบหรือจั่วไพ่ตามความน่าจะเป็น
GameB(ค่าสถิติ) //ให้ทีละใบ

**Comment by PremerX007** [comment]
เดียวเราเอา code game player ของเรามา integrate เข้าไปด้วย

**Comment by Th3than** [comment]
Done

**Comment by Th3than** [comment]
มีการเปลี่ยน bot เป็น class แต่ยังไม่ได้update ใน GameB
