### ISSUE TITLE
Propa()

### ISSUE THREAD

**Issue by SkyEngineerME** [SkyEngineerME/Blackjack#4]
ฟังก์ชั่นรับค่าเพื่อกำหนดสถิติ เช่น ต้องการให้ สุ่มช่วง 80 % ให้แสดงผลรับเป็น true หรือ false ให้รับค่า ต่ำสุด สูงสุด ค่าที่ได้แล้วใส่เงื่อนไข
เช่น (0,21,20) โอกาศเท่ากับ 95 % ที่จะหมอบ

**Comment by SkyEngineerME** [comment]
ฟังก์ชันนี้ขอให้เสร็จเร็วพิเศษหน่อยนะเพราะว่าต้องใช้เยอะ

**Comment by Th3than** [comment]
มีการเปลี่ยนGivecard เป็นการส่งว่าได้ไพ่ใบที่เท่าไหร่แทนการส่งชื่อไพ่
 มีการเพิ่มarray Cardpoint เพื่อเก็บค่าว่าไพ่ใบนี้มี แต้มเท่าไหร่ แล้ว สลับตำแหน่งshuffle พร้อม CardID
มีการเพิ่มarray playerhand และ array bothand ที่แต็มว่ามีไพ่อะไรบนมือ
function propa return  ค่าเป็น true false true หมายถึงจั่วไพ่เพิ่ม

**Comment by Th3than** [comment]
สร้าง class ชื่อบท ที่มีprivate: vector<int> bothand เก็บค่าไพ่ที่ได้ในมือโดยเก็บว่าไพ่ใบที่เท่าไหร่   bool botdraw เก็บค่าตัดสินในการจั่วไพ่เพิ่มโดยเริ่มต้น เป็น false
 public:
        bot(string [], int &); การสร้างสร้างต้องใส่ array ของ cardid และ cardn 
        void Propa(); เป็นตัดสินใจในการจั่วโดยจะส่งค่ากลับไปที่ botdraw
        int show(int); เป็นส่งค่าไพ่กลับโดยจะส่งว่าได้ใบที่เท่าของกองการ์ด และต้องใส่ค่าว่าจะดูไพ่ใบที่เท่าไหร่ของbot
        bool botact(); เรียกค่าจาก botdraw
        ~bot();
    };
