### ISSUE TITLE
Win()

### ISSUE THREAD

**Issue by SkyEngineerME** [SkyEngineerME/Blackjack#5]
เงื่อนไขที่จะนำเงินเดิมพันแต่ละคนมาเปรียบเทียบ คนเยอะสุดคือคนชนะ ถ้าคะแนนเท่ากันเท่ากับชนะร่วม

**Comment by NongFirstTH** [comment]
Finish

**Comment by NongFirstTH** [comment]
ทำฟังก์ชั่นwin เทียบBet แต่ละคนเสร็จเรียบร้อย
เหลือทำ ฟังก์ชั่นcheck scoreของผู้เล่นและbot

**Comment by NongFirstTH** [comment]
เขียนฟังก์ชั่น CheckScore() เทียบคะแนนกับDealerเรียบร้อย
โดยรับค่าInput 9 ตัว โดยที่5ตัวแรก คือ Ds(Dealer score) , Ps(Player score) , B1s(Bot1 score) , B2s(Bot2 score) , B3s(Bot3 score)
อีก 4 ตัว รับค่าcondition ในฟังก์ชั่น โดยconditionส่งintเป็น 0 คือ win , ส่งintเป็น 1 คือ draw , ส่งintเป็น 2 คือ lose
