### ISSUE TITLE
BetP()

### ISSUE THREAD

**Issue by SkyEngineerME** [SkyEngineerME/Blackjack#7]
ให้ผู้เล่นใส่ค่าลงเดิมพัน โดยห้ามเกินจำนวนเงินที่มี หรือน้อยกว่า 1

**Comment by SkyEngineerME** [comment]
เดี๋ยวพิมพ์doneในissueนี้หน่อยนะ

**Comment by TheeraphanPhanwattanasin** [comment]
Done

**Comment by SkyEngineerME** [comment]
ลองใช้โปรแกรมแล้วมีการดักเลขทศนิยมและมีการใช้สีข้อความ ยอดเยี่ยมครับ
